import type { Metadata } from "next";
import { Poppins, Space_Grotesk } from "next/font/google";
import "./globals.css";
import { ToneProvider } from "@/ui/ToneProvider";

const poppins = Poppins({
  variable: "--font-sans",
  subsets: ["latin"],
  weight: ["300","400","500","600","700"],
});

const grotesk = Space_Grotesk({
  variable: "--font-display",
  subsets: ["latin"],
  weight: ["400","500","600","700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning className={`${poppins.variable} ${grotesk.variable}`}>
        <ToneProvider>
        <div className="toolbar">
          <a href="/signin" className="brand">
            <span className="brand-dot" />
            <span>cupNgo</span>
          </a>
          <nav className="row">
            <a href="/shelf" className="subtle">Shelf</a>
          </nav>
        </div>
        {children}
        </ToneProvider>
      </body>
    </html>
  );
}
